export const ADD_QUID_TO_COLLECTION = "ADD_QUID_TO_COLLECTION";
export const REMOVE_QUID_FROM_COLLECTION = "DELETE_QUID_FROM_COLLECTION";
export const RELATE_QUID = "RELATE_QUID";
export const DISOWN_QUID = "DISOWN_QUID";